backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
#local_backend: true
media_folder: static/img
public_folder: /img

collections:
  # BLOG
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          sanitize_preview: true,
        }
      - {
          label: "Introduction",
          name: "introduction",
          widget: "text",
          # pattern:
          #   [
          #     "^.(\\/s?.){200,400}",
          #     "Must have at least 200 characters and not go over 400 characters",
          #   ],
        }
      - {
          label: "Blog Category",
          name: "categories",
          widget: "relation",
          collection: "categories",
          search_fields: ["category-name"],
          value_field: "category-name",
          display_fields: ["category-name"],
        }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "author",
          search_fields: ["display-name"],
          value_field: "{{slug}}",
          display_fields: ["display-name"],
        }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "Blog Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }

  # FEATURED BLOGS

  - label: "Featured blogs"
    name: "featured-blogs"
    files:
      - label: "Blogs to feature"
        name: "blogs-to-feature"
        file: "content/featured-blogs.json"
        create: true
        editor:
          preview: false
        fields:
          - label: "Featured blogs List"
            name: "featured-blogs"
            widget: "list"
            fields:
              - {
                  label: "Blog To Feature",
                  name: "featured-blog-id",
                  collection: "blog",
                  widget: "relation",
                  search_fields: ["title"],
                  value_field: "{{slug}}",
                  display_fields: ["title"],
                }
  #  Blog categories
  - label: "Blog categories"
    name: "categories"
    folder: "content/categories"
    widget: "list"
    create: true
    editor:
      preview: false
    slug: "{{category-name}}"
    fields:
      - { label: "Category name", name: "category-name", widget: "string" }
  # Authors
  - label: "Authors"
    name: "author"
    folder: "content/author"
    frontmatter: true
    create: true
    allow_add: true
    add_to_top: true
    identifier_field: display-name
    editor:
      preview: false
    slug: "{{display-name}}"
    fields:
      - { label: "Firstname", name: "name", widget: "string" }
      - { label: "Display Name", name: "display-name", widget: "string" }
      - {
          label: "Profile Picture",
          name: "profile-picture",
          widget: "image",
          allow_multiple: false,
        }
      - { label: "Position", name: "position", widget: "string" }
      - {
          label: "About Me",
          name: "body",
          widget: "markdown",
          sanitize_preview: true,
        }

  # ABOUT PAGE
  - name: "about-page"
    label: "About Page Content"
    folder: "content/about"
    slug: "About-page-content"
    create: false
    add_to_top: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "About me Body",
          name: "body",
          widget: "markdown",
          sanitize_preview: true,
        }
  # NAVIGATION
  - label: "Navigation Links"
    name: "navigation-links"
    files:
      - label: "Links"
        name: "links"
        file: "content/navigation.yml"
        create: true
        editor:
          preview: false
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
